# Numpy Tutorial

## Creating 1 dimensional array

In [5]:
import numpy as np

n1=np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

## Creat N-Dimensional Array

In [6]:
n2=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
type(n2)

numpy.ndarray

## Extract Array elements

In [8]:
n1

array([1, 2, 3, 4])

In [9]:
n1[1]

2

In [10]:
n1[0:3]

array([1, 2, 3])

In [11]:
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
n2[2, 1]

10

In [13]:
n2[1]

array([5, 6, 7, 8])

In [14]:
n2[0,2]

3

## Generate Zero Arrays

In [15]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [16]:
import numpy as np
n1=np.zeros((3,4))
n1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Generate Array of Range of Numbers

In [17]:
import numpy as np
n1=np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np
n1=np.arange(0,100,2)
n1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
## Generate Array of Numbers

In [20]:
import numpy as np
n1=np.full((3,5),1)
n1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Generate Array of Random Numbers

In [21]:
import numpy as np
n1=np.random.randint(1,100, (2,10))
n1

array([[25, 11, 16,  1, 48, 97, 49, 31, 79, 92],
       [ 1,  6, 17, 23, 59, 55, 78, 88, 15, 44]])

In [22]:
n1.shape

(2, 10)

In [23]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

## Reshape NumPy Shape

In [24]:
n1.shape = (2,3)
n1.shape

(2, 3)

## Sum Numpy Array

In [25]:
import numpy as np
n1=np.array([1,2])
n2=np.array([3,4])

np.sum([n1,n2])

10

In [26]:
np.sum([n1,n2],axis=0)

array([4, 6])

In [27]:
np.sum([n1,n2],axis=1)

array([3, 7])

## Compare NumPy Arrays

In [28]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([1,2,4])

np.equal(n1,n2)

array([ True,  True, False])

In [29]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([1,3,2])

np.array_equal(n1,n2)

False

## Join Arrays Vertically

In [30]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([4,5,6])

np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

## Join Arrays Columns

In [31]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([4,5,6])

np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

## Join Arrays Horizontally

In [32]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([4,5,6])

np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [33]:
import numpy as np
n1=np.array([1,2,3])
n1=n1/2
n1

array([0.5, 1. , 1.5])

In [34]:
n1=n1+1
n1

array([1.5, 2. , 2.5])

In [35]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8,9])

## Intersection of 1 dimentional array

In [36]:
np.intersect1d(n1,n2)

array([5, 6])

## Difference of 1 dimentional array

In [37]:
np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

## Standard deviation

In [38]:
import numpy as np
n1=np.array([2.1,3.2,1.23,7,4.2,75])
np.std(n1)

26.691636486610058